resource "random_id" "cloud_config" {
  byte_length = 16
}

resource "proxmox_virtual_environment_file" "cloud_config" {
  content_type = "snippets"
  datastore_id = var.cluster.cloud_config_datastore_id
  node_name    = var.cluster.target_node

  source_raw {
    data = <<EOF
#cloud-config
users:
  - default
  - name: terraform
    groups:
      - sudo
    shell: /bin/bash
    ssh_authorized_keys:
      - ${trimspace(data.local_file.ssh_public_key.content)}
    sudo: ALL=(ALL) NOPASSWD:ALL
timezone: Europe/Berlin
write_files:
  - encoding: b64
    content: ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIA0KIEBAQEBAQCAgIEBAQCAgQEBAICBAQEAgIEBAQEBAQEBAICAgQEBAQEBAICAgIEBAQEBAQCAgIEBAQEBAQEBAQEAgICBAQEBAQEBAQCAgQEBAICBAQEAgIEBAQEBAQEBAICAgQEBAQEBAICAgIEBAQEBAQCAgIA0KQEBAQEBAQEAgIEBAQCAgQEBAICBAQEAgIEBAQEBAQEBAICBAQEBAQEBAICAgQEBAQEBAQEAgIEBAQEBAQEBAQEBAICBAQEBAQEBAQCAgQEBAQCBAQEAgIEBAQEBAQEBAICBAQEBAQEBAICAgQEBAQEBAQCAgIA0KQEAhICBAQEAgIEBAISAgQEAhICBAQCEgIEBAISAgICAgICAhQEAgICAgICAgQEAhICBAQEAgIEBAISBAQCEgQEAhICBAQCEgICAgICAgQEAhQCFAQEAgIEBAISAgICAgICAhQEAgICAgICAgIUBAICAgICAgIA0KIUAhICBAIUAgICFAISAgIUAhICAhQCEgICFAISAgICAgICAhQCEgICAgICAgIUAhICBAIUAgICFAISAhQCEgIUAhICAhQCEgICAgICAgIUAhIUAhQCEgICFAISAgICAgICAhQCEgICAgICAgIUAhICAgICAgIA0KQCFAIUAhQCEgIEAhISAgISFAICBAIUAgIEAhISE6ISAgICAhIUBAISEgICAgQCFAICAhQCEgIEAhISAhIUAgQCFAICBAISEhOiEgICAgQCFAICEhQCEgIEAhISE6ISAgICAhIUBAISEgICAgISFAQCEhICAgIA0KISEhQCEhISEgICFAISAgISEhICAhQCEgICEhISEhOiAgICAgISFAISEhICAgIUAhICAhISEgICFAISAgICEgIUAhICAhISEhITogICAgIUAhICAhISEgICEhISEhOiAgICAgISFAISEhICAgICEhQCEhISAgIA0KISE6ICAhISEgICEhOiAgISE6ICAhITogICEhOiAgICAgICAgICAgICE6ISAgISE6ICAhISEgICEhOiAgICAgISE6ICAhITogICAgICAgISE6ICAhISEgICEhOiAgICAgICAgICAgICE6ISAgICAgICAhOiEgIA0KOiE6ICAhOiEgIDohOiAgOiE6ICA6ITogIDohOiAgICAgICAgICAgITohICAgOiE6ICAhOiEgIDohOiAgICAgOiE6ICA6ITogICAgICAgOiE6ICAhOiEgIDohOiAgICAgICAgICAgITohICAgICAgICE6ISAgIA0KOjogICA6OjogICA6Ojo6IDo6IDo6OiAgICA6OiA6Ojo6ICA6Ojo6IDo6ICAgOjo6OjogOjogIDo6OiAgICAgOjogICAgOjogOjo6OiAgIDo6ICAgOjogICA6OiA6Ojo6ICA6Ojo6IDo6ICAgOjo6OiA6OiAgIA0KIDogICA6IDogICAgOjogOiAgOiA6ICAgIDogOjogOjogICA6OiA6IDogICAgIDogOiAgOiAgICA6ICAgICAgOiAgICA6IDo6IDo6ICAgOjogICAgOiAgIDogOjogOjogICA6OiA6IDogICAgOjogOiA6
    owner: root:root
    path: /etc/motd
    permissions: "0644"

packages:
  - qemu-guest-agent
  - net-tools
package_upgrade: true
runcmd:
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent
  - apt update
  - apt upgrade -y
  - echo "done" > /tmp/cloud-config.done
EOF
    file_name = "cloud-config-${random_id.cloud_config.hex}.yaml"
  }
}
